config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'

  get '/faq', to: 'static_pages#faq'
  get '/about', to: 'static_pages#about'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def faq
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # Returns the full title of a page, defaulting to the site name.
  def full_title(page_title = '')
    base_title = "Strava Activity Titler"
    if page_title.empty?
      base_title
    else
      "#{page_title} | #{base_title}"
    end
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_footer.html.erb
<footer>
  <nav>
    <ul>
      <li><%= link_to "About", about_path %></li>
    </ul>
  </nav>
  <%= link_to image_tag(
          "strava/pwrdBy_strava/pwrdBy_strava_gray/api_logo_pwrdBy_strava_horiz_gray.png", 
          height: '36',
          alt: "Powered by Strava"
        ), 'https://www.strava.com/' %>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Strava Activity Titler", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "FAQ", faq_path %></li>
        <li><%= link_to "Log In", '#' %></li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>

<%= stylesheet_link_tag 'application',
                        media: 'all',
                        'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application',
                        'data-turbolinks-track': 'reload' %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title><%= full_title(yield(:title)) %></title>
  <%= render 'layouts/rails_default' %>
  <%= render 'layouts/shim' %>
</head>

<body>
  <%= render 'layouts/header' %>
  <div class="container">
    <%= yield %>
    <%= render 'layouts/footer' %>
  </div>
</body>
</html>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>

<h1>About</h1>

<p>Strava Activity Titler is a service created by Oliver Newman.</p>

app/views/static_pages/faq.html.erb
<% provide(:title, "FAQ") %>

<h1>FAQ</h1>

<p>Frequently Asked Questions coming soon</p>

app/views/static_pages/home.html.erb
<div class="center jumbotron">
  <h1>Welcome to the Strava Activity Titler!</h1>

  <p>
    Strava Activity Titler is a service that uses the Strava API to
    automatically modify the default titles of a user's activities, based on a
    set of rules defined by the user.
  </p>

  <%= link_to image_tag(
                "strava/btn_strava_connectwith_light/btn_strava_connectwith_light@2x.png",
                alt: "Connect with Strava"
              ), '#', class: "btn" %>
</div>